/*
 * Stress Corrosion Cracking Modeller
 */
package ru.gss.sccmodeller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import ru.gss.sccmodeller.commons.DlgParent;

/**
 * About dialog.
 * @version 1.1.0 19.03.2020
 * @author Sergey Guskov
 */
public class SCCModellerAboutBox extends DlgParent {

    /**
     * Constructor.
     */
    public SCCModellerAboutBox() {
        super();
        initComponents();
        jlbAppDeveloper.setVisible(false);
        getRootPane().registerKeyboardAction(new ActionListener() {
            public void actionPerformed(final ActionEvent e) {
                jlbAppDeveloper.setVisible(!jlbAppDeveloper.isVisible());
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_1, InputEvent.CTRL_DOWN_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);
        getRootPane().setDefaultButton(jbtnClose);
    }

    /**
     * Action for Close button.
     */
    @Action
    public void acClose() {
        dispose();
    }

    //CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnClose = new javax.swing.JButton();
        javax.swing.JLabel jlbAppTitle = new javax.swing.JLabel();
        javax.swing.JLabel jlbAppVersion = new javax.swing.JLabel();
        javax.swing.JLabel jlbAppDescription1 = new javax.swing.JLabel();
        jlbAppDeveloper = new javax.swing.JLabel();
        javax.swing.JLabel jlbAppDescription2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JLabel jlbImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ru.gss.sccmodeller.SCCModellerApp.class).getContext().getResourceMap(SCCModellerAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ru.gss.sccmodeller.SCCModellerApp.class).getContext().getActionMap(SCCModellerAboutBox.class, this);
        jbtnClose.setAction(actionMap.get("acClose")); // NOI18N
        jbtnClose.setText(resourceMap.getString("jbtnClose.text")); // NOI18N
        jbtnClose.setName("jbtnClose"); // NOI18N

        jlbAppTitle.setFont(jlbAppTitle.getFont().deriveFont(jlbAppTitle.getFont().getStyle() | java.awt.Font.BOLD, jlbAppTitle.getFont().getSize()+4));
        jlbAppTitle.setText(resourceMap.getString("Application.title")); // NOI18N
        jlbAppTitle.setName("jlbAppTitle"); // NOI18N

        jlbAppVersion.setFont(jlbAppVersion.getFont().deriveFont(jlbAppVersion.getFont().getStyle() & ~java.awt.Font.BOLD));
        jlbAppVersion.setText(resourceMap.getString("jlbAppVersion.text")); // NOI18N
        jlbAppVersion.setName("jlbAppVersion"); // NOI18N

        jlbAppDescription1.setText(resourceMap.getString("jlbAppDescription1.text")); // NOI18N
        jlbAppDescription1.setName("jlbAppDescription1"); // NOI18N

        jlbAppDeveloper.setText(resourceMap.getString("jlbAppDeveloper.text")); // NOI18N
        jlbAppDeveloper.setName("jlbAppDeveloper"); // NOI18N

        jlbAppDescription2.setText(resourceMap.getString("jlbAppDescription2.text")); // NOI18N
        jlbAppDescription2.setName("jlbAppDescription2"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(375, 2));

        jSeparator2.setName("jSeparator2"); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(375, 2));

        jlbImage.setIcon(resourceMap.getIcon("jlbImage.icon")); // NOI18N
        jlbImage.setName("jlbImage"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAppDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAppTitle)
                    .addComponent(jlbAppVersion)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtnClose)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbAppDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAppDeveloper))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbAppDescription1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbAppDescription2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbAppVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbAppDeveloper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jbtnClose)
                .addContainerGap())
            .addComponent(jlbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JLabel jlbAppDeveloper;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON
}
